---
Name: subsitedefaultemailconfig
Before:
  - coreconfig
---
SilverStripe\Subsites\Model\Subsite:
  extensions:
    - DNADesign\SubsitesDefaultEmails\Extension\DefaultEmailExtension

SilverStripe\Control\Email\MailerSubscriber:
  extensions:
    - DNADesign\SubsitesDefaultEmails\Extension\MailSubscriberExtension
