---
Name: subsitedefaultemailconfig
Before:
  - coreconfig
---
SilverStripe\Subsites\Model\Subsite:
  extensions:
    - DNADesign\SubsitesDefaultEmails\Extension\DefaultEmailExtension

SilverStripe\Control\Email\Email:
  extensions:
    - DNADesign\SubsitesDefaultEmails\Extension\EmailExtension
